/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import java.awt.event.KeyEvent;

/**
 *
 * @author User
 */
public class principal extends javax.swing.JFrame {
    //Atributos para guardarmos numero digitado e registrar a operação selecionada
    double numero = 0;
    int operacao = 0;
    
    //Para a operação:
    // 1 - soma
    // 2 - subtração
    // 3 - multiplicação
    // 4 - divisão
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(principal.class.getName());

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JTextField();
        soma = new javax.swing.JButton();
        subtracao = new javax.swing.JButton();
        multiplicacao = new javax.swing.JButton();
        divisao = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        numero1 = new javax.swing.JButton();
        numero2 = new javax.swing.JButton();
        numero3 = new javax.swing.JButton();
        numero4 = new javax.swing.JButton();
        numero5 = new javax.swing.JButton();
        numero6 = new javax.swing.JButton();
        numero7 = new javax.swing.JButton();
        numero8 = new javax.swing.JButton();
        numero9 = new javax.swing.JButton();
        numero0 = new javax.swing.JButton();
        virgula = new javax.swing.JButton();
        limpar_tudo = new javax.swing.JButton();
        mais_menos = new javax.swing.JButton();
        potenciaquadrada = new javax.swing.JButton();
        potencia = new javax.swing.JButton();
        raizquadrada = new javax.swing.JButton();
        umsobx = new javax.swing.JButton();
        porcentagem = new javax.swing.JButton();
        historico = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        display.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        display.setBorder(null);
        display.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                displayKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                displayKeyTyped(evt);
            }
        });

        soma.setBackground(java.awt.Color.gray);
        soma.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        soma.setText("+");
        soma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        soma.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        soma.setMaximumSize(new java.awt.Dimension(33, 33));
        soma.setMinimumSize(new java.awt.Dimension(33, 33));
        soma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                somaMouseClicked(evt);
            }
        });

        subtracao.setBackground(java.awt.Color.gray);
        subtracao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subtracao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        subtracao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        subtracao.setLabel("-");
        subtracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subtracaoMouseClicked(evt);
            }
        });

        multiplicacao.setBackground(java.awt.Color.gray);
        multiplicacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        multiplicacao.setText("*");
        multiplicacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        multiplicacao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        multiplicacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplicacaoMouseClicked(evt);
            }
        });

        divisao.setBackground(java.awt.Color.gray);
        divisao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        divisao.setText("/");
        divisao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        divisao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        divisao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divisaoMouseClicked(evt);
            }
        });

        igual.setBackground(java.awt.Color.gray);
        igual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        igual.setText("=");
        igual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        igual.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        igual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                igualMouseClicked(evt);
            }
        });

        limpar.setBackground(java.awt.Color.gray);
        limpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        limpar.setText("CE");
        limpar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        limpar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        limpar.setMaximumSize(new java.awt.Dimension(60, 35));
        limpar.setMinimumSize(new java.awt.Dimension(60, 35));
        limpar.setPreferredSize(new java.awt.Dimension(60, 35));
        limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limparMouseClicked(evt);
            }
        });

        numero1.setBackground(java.awt.Color.gray);
        numero1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numero1.setText("1");
        numero1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        numero1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numero1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numero1MouseClicked(evt);
            }
        });

        numero2.setBackground(java.awt.Color.gray);
        numero2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numero2.setText("2");
        numero2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        numero2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numero2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numero2MouseClicked(evt);
            }
        });

        numero3.setBackground(java.awt.Color.gray);
        numero3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numero3.setText("3");
        numero3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        numero3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numero3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numero3MouseClicked(evt);
            }
        });

        numero4.setBackground(java.awt.Color.gray);
        numero4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numero4.setText("4");
        numero4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        numero4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numero4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numero4MouseClicked(evt);
            }
        });

        numero5.setBackground(java.awt.Color.gray);
        numero5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numero5.setText("5");
        numero5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        numero5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numero5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numero5MouseClicked(evt);
            }
        });

        numero6.setBackground(java.awt.Color.gray);
        numero6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numero6.setText("6");
        numero6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        numero6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numero6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numero6MouseClicked(evt);
            }
        });

        numero7.setBackground(java.awt.Color.gray);
        numero7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numero7.setText("7");
        numero7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        numero7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numero7.setMaximumSize(new java.awt.Dimension(60, 35));
        numero7.setMinimumSize(new java.awt.Dimension(60, 35));
        numero7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numero7MouseClicked(evt);
            }
        });

        numero8.setBackground(java.awt.Color.gray);
        numero8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numero8.setText("8");
        numero8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        numero8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numero8.setMaximumSize(new java.awt.Dimension(60, 35));
        numero8.setMinimumSize(new java.awt.Dimension(60, 35));
        numero8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numero8MouseClicked(evt);
            }
        });

        numero9.setBackground(java.awt.Color.gray);
        numero9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numero9.setText("9");
        numero9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        numero9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numero9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numero9MouseClicked(evt);
            }
        });

        numero0.setBackground(java.awt.Color.gray);
        numero0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numero0.setText("0");
        numero0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        numero0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numero0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numero0MouseClicked(evt);
            }
        });

        virgula.setBackground(java.awt.Color.gray);
        virgula.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        virgula.setText(",");
        virgula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        virgula.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        virgula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                virgulaMouseClicked(evt);
            }
        });

        limpar_tudo.setBackground(java.awt.Color.gray);
        limpar_tudo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        limpar_tudo.setText("C");
        limpar_tudo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        limpar_tudo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        limpar_tudo.setMaximumSize(new java.awt.Dimension(60, 35));
        limpar_tudo.setMinimumSize(new java.awt.Dimension(60, 35));
        limpar_tudo.setPreferredSize(new java.awt.Dimension(60, 35));
        limpar_tudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpar_tudoMouseClicked(evt);
            }
        });

        mais_menos.setBackground(java.awt.Color.gray);
        mais_menos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mais_menos.setText("+/-");
        mais_menos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        mais_menos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mais_menos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mais_menosMouseClicked(evt);
            }
        });

        potenciaquadrada.setBackground(java.awt.Color.gray);
        potenciaquadrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        potenciaquadrada.setText("x²");
        potenciaquadrada.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        potenciaquadrada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        potenciaquadrada.setMaximumSize(new java.awt.Dimension(60, 35));
        potenciaquadrada.setMinimumSize(new java.awt.Dimension(60, 35));
        potenciaquadrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                potenciaquadradaMouseClicked(evt);
            }
        });

        potencia.setBackground(java.awt.Color.gray);
        potencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        potencia.setText("x^y");
        potencia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        potencia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        potencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                potenciaMouseClicked(evt);
            }
        });

        raizquadrada.setBackground(java.awt.Color.gray);
        raizquadrada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        raizquadrada.setText("sqrt");
        raizquadrada.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        raizquadrada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        raizquadrada.setMaximumSize(new java.awt.Dimension(60, 35));
        raizquadrada.setMinimumSize(new java.awt.Dimension(60, 35));
        raizquadrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raizquadradaMouseClicked(evt);
            }
        });

        umsobx.setBackground(java.awt.Color.gray);
        umsobx.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        umsobx.setText("1/X");
        umsobx.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        umsobx.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        umsobx.setMaximumSize(new java.awt.Dimension(60, 35));
        umsobx.setMinimumSize(new java.awt.Dimension(60, 35));
        umsobx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                umsobxMouseClicked(evt);
            }
        });

        porcentagem.setBackground(java.awt.Color.gray);
        porcentagem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        porcentagem.setText("%");
        porcentagem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(51, 51, 51)));
        porcentagem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        porcentagem.setMaximumSize(new java.awt.Dimension(60, 35));
        porcentagem.setMinimumSize(new java.awt.Dimension(60, 35));
        porcentagem.setPreferredSize(new java.awt.Dimension(60, 35));
        porcentagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                porcentagemMouseClicked(evt);
            }
        });

        historico.setBackground(new java.awt.Color(255, 255, 255));
        historico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        historico.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(historico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(display)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(numero1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(numero4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mais_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(numero7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numero0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(numero5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(numero8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(virgula, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numero6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numero9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(numero3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(soma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(potencia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(porcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(umsobx, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(limpar_tudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(potenciaquadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(raizquadrada, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(historico, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(umsobx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(porcentagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpar_tudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(potencia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(potenciaquadrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(raizquadrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soma, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mais_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numero0, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(virgula, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void somaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_somaMouseClicked
        // TODO add your handling code here:
        numero = Double.parseDouble(display.getText());
        operacao = 1;
        historico.setText("" + display.getText() + " + ");
        display.setText("");
    }//GEN-LAST:event_somaMouseClicked

    private void igualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igualMouseClicked
        // TODO add your handling code here:
        if(operacao==1){
            double resultado = numero + Double.parseDouble(display.getText());
            historico.setText("" + historico.getText() + display.getText() +  " = ");
            display.setText("" + resultado);
        } else if (operacao==2){
            double resultado = numero - Double.parseDouble(display.getText());
            historico.setText("" + historico.getText() + display.getText() +  " = ");
            display.setText("" + resultado);
        } else if (operacao==3){
            double resultado = numero * Double.parseDouble(display.getText());
            historico.setText("" + historico.getText() + display.getText() +  " = ");
            display.setText("" + resultado);
        } else if(operacao==4){
            if(Double.parseDouble(display.getText()) != 0){
                double resultado = numero / Double.parseDouble(display.getText());
                historico.setText("" + historico.getText() + display.getText() +  " = ");
                display.setText("" + resultado);
            } else {
                display.setText("Não é possível dividir por 0");
            }
        } else if (operacao==5){
            double resultado = Math.pow(numero,Double.parseDouble(display.getText()));
            historico.setText("" + historico.getText() + display.getText() +  " = ");
            display.setText("" + resultado);
        }
    }//GEN-LAST:event_igualMouseClicked

    private void limparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limparMouseClicked
        // TODO add your handling code here:
        display.setText("");
    }//GEN-LAST:event_limparMouseClicked

    private void numero1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numero1MouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "1");
    }//GEN-LAST:event_numero1MouseClicked

    private void numero2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numero2MouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "2");
    }//GEN-LAST:event_numero2MouseClicked

    private void numero3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numero3MouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "3");
    }//GEN-LAST:event_numero3MouseClicked

    private void numero4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numero4MouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "4");
    }//GEN-LAST:event_numero4MouseClicked

    private void numero5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numero5MouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "5");
    }//GEN-LAST:event_numero5MouseClicked

    private void numero6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numero6MouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "6");
    }//GEN-LAST:event_numero6MouseClicked

    private void numero7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numero7MouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "7");
    }//GEN-LAST:event_numero7MouseClicked

    private void numero8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numero8MouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "8");
    }//GEN-LAST:event_numero8MouseClicked

    private void numero9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numero9MouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "9");
    }//GEN-LAST:event_numero9MouseClicked

    private void numero0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numero0MouseClicked
        // TODO add your handling code here:
        display.setText(display.getText() + "0");
    }//GEN-LAST:event_numero0MouseClicked

    private void subtracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtracaoMouseClicked
        // TODO add your handling code here:
        numero = Double.parseDouble(display.getText());
        operacao = 2;
        historico.setText("" + display.getText() + " - ");
        display.setText("");     
    }//GEN-LAST:event_subtracaoMouseClicked

    private void multiplicacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicacaoMouseClicked
        // TODO add your handling code here:
        numero = Double.parseDouble(display.getText());
        operacao = 3;
        historico.setText("" + display.getText() + " * ");
        display.setText("");
    }//GEN-LAST:event_multiplicacaoMouseClicked

    private void divisaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisaoMouseClicked
        // TODO add your handling code here:
        numero = Double.parseDouble(display.getText());
        operacao = 4;
        historico.setText("" + display.getText() + " / ");
        display.setText("");
    }//GEN-LAST:event_divisaoMouseClicked

    private void virgulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_virgulaMouseClicked
        // TODO add your handling code here:
        if(!display.getText().contains(".")){
            display.setText(display.getText() + ".");
        }
    }//GEN-LAST:event_virgulaMouseClicked

    private void limpar_tudoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpar_tudoMouseClicked
        // TODO add your handling code here:
        numero = 0;
        operacao = 0;
        historico.setText("");
        display.setText("");
    }//GEN-LAST:event_limpar_tudoMouseClicked

    private void mais_menosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mais_menosMouseClicked
        // TODO add your handling code here:
        numero = Double.parseDouble(display.getText()) * (-1);
        display.setText("" + numero);
        //String texto = display.getText();
        
        //if(texto.startsWith("-")){
        //    display.setText(texto.substring(1));
        // } else {
        //    display.setText("-" + display.getText());
        //}
        //startsWith("-") → verifica se já é negativo
        //substring(1) → remove o primeiro caractere (-)
    }//GEN-LAST:event_mais_menosMouseClicked

    private void displayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(Character.isDigit(c) || c == '.'){
            
        } else {
            evt.consume();
        }
        //Character.isDigit(c) → aceita números
        //evt.consume() → ignora a tecla inválida
        //evt.getKeyChar() → cria um objeto de evento (evt) com informações sobre essa tecla.
    }//GEN-LAST:event_displayKeyTyped

    private void potenciaquadradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potenciaquadradaMouseClicked
        // TODO add your handling code here:
        numero = Double.parseDouble(display.getText());
        double resultado = Math.pow(numero,2);
        display.setText("" + resultado);
        
    }//GEN-LAST:event_potenciaquadradaMouseClicked

    private void potenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potenciaMouseClicked
        // TODO add your handling code here:
        numero = Double.parseDouble(display.getText());
        operacao = 5;
        historico.setText("" + display.getText() + " ^ ");
        display.setText("");
    }//GEN-LAST:event_potenciaMouseClicked

    private void raizquadradaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raizquadradaMouseClicked
        // TODO add your handling code here:
        numero = Double.parseDouble(display.getText());
        double resultado = Math.sqrt(numero);
        display.setText("" + resultado);
    }//GEN-LAST:event_raizquadradaMouseClicked

    private void umsobxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_umsobxMouseClicked
        // TODO add your handling code here:
        
        if(Double.parseDouble(display.getText()) != 0){
                numero = Double.parseDouble(display.getText());
                double resultado = 1 / (numero);
                display.setText("" + resultado);
            } else {
                display.setText("Não é possível dividir por 0");
            }
    }//GEN-LAST:event_umsobxMouseClicked

    private void porcentagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_porcentagemMouseClicked
        // TODO add your handling code here:
        double porcento = numero*(Double.parseDouble(display.getText())/100);
        display.setText("" + porcento);
    }//GEN-LAST:event_porcentagemMouseClicked

    private void displayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayKeyPressed
        // TODO add your handling code here:
        int tecla = evt.getKeyCode();
        char c = evt.getKeyChar();

        if(c == '+'){
            numero = Double.parseDouble(display.getText());
            operacao = 1;
            historico.setText(display.getText() + " + ");
            display.setText("");
        } else if(c == '-'){
            numero = Double.parseDouble(display.getText());
            operacao = 2;
            historico.setText(display.getText() + " - ");
            display.setText("");
        } else if(c == '*'){
            numero = Double.parseDouble(display.getText());
            operacao = 3;
            historico.setText(display.getText() + " * ");
            display.setText("");
        } else if(c == '/'){
            numero = Double.parseDouble(display.getText());
            operacao = 4;
            historico.setText(display.getText() + " / ");
            display.setText("");
        } else if(tecla == KeyEvent.VK_ENTER){
            switch(operacao){
                case 1:
                double r = numero + Double.parseDouble(display.getText());
                historico.setText("" + historico.getText() + display.getText() +  " = ");
                display.setText("" + r);
                break;
            

            case 2:
                r = numero - Double.parseDouble(display.getText());
                historico.setText("" + historico.getText() + display.getText() +  " = ");
                display.setText("" + r);
                break;
            

            case 3:
                r = numero * Double.parseDouble(display.getText());
                historico.setText("" + historico.getText() + display.getText() +  " = ");
                display.setText("" + r);
                break;
            

            case 4:

                if(Double.parseDouble(display.getText()) != 0){

                    r = numero / Double.parseDouble(display.getText());
                    historico.setText("" + historico.getText() + display.getText() +  " = ");
                    display.setText("" + r);

                } else {

                    display.setText("Não é possível dividir por 0");
                }
                break;
            
            }
        }  
    }//GEN-LAST:event_displayKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField display;
    private javax.swing.JButton divisao;
    private javax.swing.JLabel historico;
    private javax.swing.JButton igual;
    private javax.swing.JButton limpar;
    private javax.swing.JButton limpar_tudo;
    private javax.swing.JButton mais_menos;
    private javax.swing.JButton multiplicacao;
    private javax.swing.JButton numero0;
    private javax.swing.JButton numero1;
    private javax.swing.JButton numero2;
    private javax.swing.JButton numero3;
    private javax.swing.JButton numero4;
    private javax.swing.JButton numero5;
    private javax.swing.JButton numero6;
    private javax.swing.JButton numero7;
    private javax.swing.JButton numero8;
    private javax.swing.JButton numero9;
    private javax.swing.JButton porcentagem;
    private javax.swing.JButton potencia;
    private javax.swing.JButton potenciaquadrada;
    private javax.swing.JButton raizquadrada;
    private javax.swing.JButton soma;
    private javax.swing.JButton subtracao;
    private javax.swing.JButton umsobx;
    private javax.swing.JButton virgula;
    // End of variables declaration//GEN-END:variables
}
